package io.github.hvogel.clientes.service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;

import com.spire.doc.Bookmark;
import com.spire.doc.Document;
import com.spire.doc.FileFormat;
import com.spire.doc.Section;
import com.spire.doc.documents.BookmarksNavigator;
import com.spire.doc.documents.BuiltinStyle;
import com.spire.doc.documents.Paragraph;
import com.spire.doc.fields.TextRange;
import com.spire.doc.interfaces.IDocument;

import io.github.hvogel.clientes.util.Messages;

@Service
public class DocService {

    private static final String SIMPLE_BOOKMARK = Messages.SIMPLE_BOOKMARK;
    private static final String ADD_BOOKMARKS_DOCX = Messages.ADD_BOOKMARKS_FILE;
    private static final String NESTED_LEVEL_1 = "NestedLevel1";
    private static final String NESTED_LEVEL_2 = "NestedLevel2";
    private static final String ROOT = "Root";

    private static final Logger LOGGER = LoggerFactory.getLogger(DocService.class);

    public void addBookmarks() {
        // Create a Document object
        Document document = new Document();
        // Add a section
        Section section = document.addSection();

        // Add a paragraph
        Paragraph paragraph = section.addParagraph();
        TextRange txtRange = paragraph
                .appendText("The following example demonstrates how to create bookmark in a Word document.");
        txtRange.getCharacterFormat().setItalic(true);

        // Add a paragraph
        section.addParagraph();
        paragraph = section.addParagraph();
        txtRange = paragraph.appendText("Simple Bookmark.");
        txtRange.getCharacterFormat().setTextColor(new Color(100, 149, 237));
        paragraph.applyStyle(BuiltinStyle.Heading_2);

        // Create a simple bookmark
        section.addParagraph();
        paragraph = section.addParagraph();
        paragraph.appendBookmarkStart(SIMPLE_BOOKMARK);
        paragraph.appendText("This is a simple bookmark.");
        paragraph.appendHTML("<p>This Bookmark has been <span>Edited</span></p>");
        paragraph.appendHTML("<hr>");
        paragraph.appendHTML(
                "<br><p><span style=\"color: blue;\">This is also Generated by Decoding HTML Code</span></p>");
        paragraph.appendBookmarkEnd(SIMPLE_BOOKMARK);

        // Add a paragraph
        section.addParagraph();
        paragraph = section.addParagraph();
        txtRange = paragraph.appendText("Nested Bookmark.");
        txtRange.getCharacterFormat().setTextColor(new Color(100, 149, 237));
        paragraph.applyStyle(BuiltinStyle.Heading_2);

        // Create nested bookmarks
        section.addParagraph();
        paragraph = section.addParagraph();
        paragraph.appendBookmarkStart(ROOT);
        txtRange = paragraph.appendText(" This is Root data. ");
        txtRange.getCharacterFormat().setItalic(true);
        paragraph.appendBookmarkStart(NESTED_LEVEL_1);
        txtRange = paragraph.appendText(" This is Nested Level1. ");
        txtRange.getCharacterFormat().setItalic(true);
        txtRange.getCharacterFormat().setTextColor(new Color(40, 79, 79));
        paragraph.appendBookmarkStart(NESTED_LEVEL_2);
        txtRange = paragraph.appendText(" This is Nested Level2. ");
        txtRange.getCharacterFormat().setItalic(true);
        txtRange.getCharacterFormat().setTextColor(new Color(105, 105, 105));
        paragraph.appendBookmarkEnd(NESTED_LEVEL_2);
        paragraph.appendBookmarkEnd(NESTED_LEVEL_1);
        paragraph.appendBookmarkEnd(ROOT);

        // Save the resultant document
        document.saveToFile(ADD_BOOKMARKS_DOCX, FileFormat.Docx_2013);
    }

    public void replaceBookmark() {
        // Load the Word document
        Document doc = new Document(ADD_BOOKMARKS_DOCX);

        // locate the bookmark.Messages.SIMPLE_BOOKMARK
        BookmarksNavigator bookmarkNavigator = new BookmarksNavigator(doc);
        bookmarkNavigator.moveToBookmark(SIMPLE_BOOKMARK);

        // replace the content of the bookmark with new content
        bookmarkNavigator.replaceBookmarkContent("This is replaced content.", false);

        // save the resultant document
        doc.saveToFile("ReplaceBookmarkContent.docx", FileFormat.Docx_2013);
    }

    public void removeBookmark() {
        // load the Word document
        Document document = new Document(ADD_BOOKMARKS_DOCX);

        // get the bookmark by name.
        Bookmark bookmark = document.getBookmarks().get(SIMPLE_BOOKMARK);

        // remove the bookmark, not its content.
        document.getBookmarks().remove(bookmark);

        // save the document.
        document.saveToFile("RemoveBookmarks.docx", FileFormat.Docx_2013);
    }

    public void changeHTML() {

        String html1 = "<p><span style=\"color: blue;\">This is the HTML 1 bla bla bla bla bla bla bla</span></p>";
        String html2 = "<ol>\\r\\n"
                + "\\t<li>This is a CKEditor 4 WYSIWYG editor instance<strong> created with Angular.</strong></li>\\r\\n"
                + "\\t<li><strong>dsfdsfsdfdsfdsfdsfdf</strong>dfsfsdfdsfdfdfh&nbsp; dfgdgdfgfdgdfgfd.</li>\\r\\n"
                + "</ol>\\r\\n";
        String html3 = "<div align=\"center\">Teste com <b>negrito </b>e <font color=\"#ff0000\"><b><i>outras </i></b></font><font face=\"Arial\" size=\"6\">formata&#231;&#245;es </font><font color=\"#6861fc\" face=\"Calibri\" size=\"5\">relacionadas</font>.<br></div> \\r\\n";

        final Document docHtml1 = new Document();
        docHtml1.addSection().addParagraph().appendHTML(html1);
        final IDocument replaceDoc1 = docHtml1;

        final Document docHtml2 = new Document();
        docHtml2.addSection().addParagraph().appendHTML(html2);
        final IDocument replaceDoc2 = docHtml2;

        final Document docHtml3 = new Document();
        docHtml3.addSection().addParagraph().appendHTML(html3);
        final IDocument replaceDoc3 = docHtml3;

        Document document = new Document("DF1.docx");
        document.replace("${3.3.5.-description}", replaceDoc1, false, true);
        document.replace("${1.3.2.-description}", replaceDoc2, false, true);
        document.replace("${1.3.4.-description}", replaceDoc3, false, true);

        document.saveToFile("savechange2.docx", FileFormat.Docx_2013);

    }

    public static byte[] convertToByteArray(Document document, FileFormat fileFormat) throws IOException {
        byte[] byteArray;
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            document.saveToStream(outputStream, fileFormat);
            byteArray = outputStream.toByteArray();
        }
        return byteArray;
    }

    public byte[] loadHTML() {

        String html1 = "<p><span style=\"color: blue;\">This is the HTML 1 bla bla bla bla bla bla bla</span></p>";
        String html2 = "<ol>\\r\\n"
                + "\\t<li>This is a CKEditor 4 WYSIWYG editor instance<strong> created with Angular.</strong></li>\\r\\n"
                + "\\t<li><strong>dsfdsfsdfdsfdsfdsfdf</strong>dfsfsdfdsfdfdfh&nbsp; dfgdgdfgfdgdfgfd.</li>\\r\\n"
                + "</ol>\\r\\n";
        String html3 = "<div align=\"center\">Teste com <b>negrito </b>e <font color=\"#ff0000\"><b><i>outras </i></b></font><font face=\"Arial\" size=\"6\">formata&#231;&#245;es </font><font color=\"#6861fc\" face=\"Calibri\" size=\"5\">relacionadas</font>.<br></div> \\r\\n";

        final Document docHtml1 = new Document();
        docHtml1.addSection().addParagraph().appendHTML(html1);
        final IDocument replaceDoc1 = docHtml1;

        final Document docHtml2 = new Document();
        docHtml2.addSection().addParagraph().appendHTML(html2);
        final IDocument replaceDoc2 = docHtml2;

        final Document docHtml3 = new Document();
        docHtml3.addSection().addParagraph().appendHTML(html3);
        final IDocument replaceDoc3 = docHtml3;

        byte[] docBytes = null;

        Document document = new Document("Paipa_Modelo.docx");
        document.replace("${1}", replaceDoc1, false, true);
        document.replace("${2}", replaceDoc2, false, true);
        document.replace("${3}", replaceDoc3, false, true);
        try {
            docBytes = convertToByteArray(document, FileFormat.Docx_2013);
        } catch (IOException e) {
            LOGGER.error("Error converting document to byte array: {}", e.getMessage());
        }
        return docBytes;
    }

}
